apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - |
          sleep 10
          yarn run migrate
          yarn run seed
        image: rafmme/neon_ah_backend
        name: backend
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
