apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Neon AH Deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: Neon-AH
    spec:
      containers:
      - name: neon_ah_db
        image: rafmme/neon_ah_database
        ports:
        - containerPort: 6000

      - name: neon_ah_frontend
        image: rafmme/neon_ah_frontend
        ports:
        - containerPort: 3110

      - name: neon_ah_backend
        image: rafmme/neon_ah_backend
        ports:
        - containerPort: 4000
